pipeline {
    agent any
    //  environment {
    //     // Define the environment variables for Maven and Java
    //     JAVA_HOME = '/usr/lib/jvm/java-17-openjdk' // Update with your Java installation directory
    //     PATH = "$JAVA_HOME/bin:$PATH"
    //     MAVEN_HOME = '/usr/share/maven' // Update with your Maven installation directory
    //     PATH = "$MAVEN_HOME/bin:$PATH"
    // }


    stages {
        stage('Checkout') {
            steps {
              git branch: 'main', url: 'https://github.com/devsecopsmurali/Java_Maven_Demo.git'
           }
        }
        stage('Build') { 
            steps {
                sh 'mvn -B -DskipTests clean package' 
            }
        }
       stage('Maven') {
            steps {
                 script {
                    sh 'mvn clean package'
                }
            }
        }
    }
}
